// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "aws-lambda-dynamodb-reto",
    "version": "1"
  },
  "paths": {
    "/planet": {
      "post": {
        "summary": "CrearPlanetaController",
        "description": "",
        "operationId": "CrearPlanetaController.post./planet",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/planet/{id}": {
      "get": {
        "summary": "ObtenerPlanetaController",
        "description": "",
        "operationId": "ObtenerPlanetaController.get./planet/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "put": {
        "summary": "ActualizarPlanetaController",
        "description": "",
        "operationId": "ActualizarPlanetaController.put./planet/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "delete": {
        "summary": "EliminarPlanetaController",
        "description": "",
        "operationId": "EliminarPlanetaController.delete./planet/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/planets": {
      "get": {
        "summary": "ObtenerPlanetasController",
        "description": "",
        "operationId": "ObtenerPlanetasController.get./planets",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/swapi-planets/{id}": {
      "get": {
        "summary": "SwapiController",
        "description": "",
        "operationId": "SwapiController.get./swapi-planets/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};